name: todoapp

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/todoapp.yml'
      - 'pkg/universe.dagger.io/examples/todoapp/**'

env:
  # This needs to be unique across all of Netlify
  APP_NAME: todoapp-dagger-europa
  NETLIFY_TEAM: blocklayer
  # https://app.netlify.com/user/applications/personal
  NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
  DAGGER_LOG_FORMAT: plain

jobs:
  dagger:
    name: "Deploy todoapp to Netlify"
    runs-on: ubuntu-latest
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # TODO: maybe use Dagger action post 0.2.0-beta.1
      - name: "Setup Go"
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: "Install dev Dagger"
        run: |
          make dagger

      - name: "Dagger"
        run: |
          cd pkg/universe.dagger.io/examples/todoapp
          ${{ github.workspace }}/cmd/dagger/dagger do deploy
